# CI pipeline. Publish is done automatially in GitHub Actions

name: $(Date:yyyy)$(Date:.M)$(Date:.d)$(Rev:.r)-rolling

variables:
  - name: buildConfiguration
    value: Release
  - name: nugetOutputPath
    value: $(Build.StagingDirectory)/nupkgs

trigger:
  batch: true
  branches:
    include:
      - master
pr:
  autoCancel: true
  branches:
    include:
      - master

pool:
  vmImage: windows-2019

jobs:
  - job: "BuildNuGets"
    displayName: "Build NuGet packages"
    workspace:
      clean: outputs
    variables:
      nugetOutputPath: "$(Build.StagingDirectory)/nupkgs"
    steps:
      - checkout: self
        clean: true

      - task: UseDotNet@2
        displayName: "Check .NETCore SDK"
        inputs:
          version: "3.1.x"
      - task: UseDotNet@2
        displayName: Check .NET5 SDK
        inputs:
          version: 5.x

      - task: NuGetToolInstaller@1
        displayName: Check NuGet client
        inputs:
          versionSpec: 5.x
          checkLatest: true

      - task: PowerShell@2
        displayName: Generate bindings
        inputs:
          targetType: filePath
          workingDirectory: Generator/
          filePath: Generator/Generate-Bindings-Imgui.ps1
          arguments: -BuildConfiguration $(buildConfiguration)

      - task: PowerShell@2
        displayName: Generate NuGet packages
        inputs:
          targetType: filePath
          workingDirectory: Generator/
          filePath: Generator/Generate-NuGets-Imgui.ps1
          arguments: -Version $(Build.BuildNumber) -Outputfolder $(nugetOutputPath) -BuildConfiguration $(buildConfiguration)

      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: NuGets"
        inputs:
          PathtoPublish: $(nugetOutputPath)
          ArtifactName: NuGets
