name: Binding Nugets
description: Generate and build bindings
inputs:
  ImX:
    description: "Values: 'Imgui', 'Imguizmo', 'Imnodes' or 'Implot'. Default 'Imgui'"
    required: false
    default: Imgui
  NugetsPath:
    description: "Local path to deliver the nugets"
    required: false
    default: "nupkgs"
runs:
  using: composite
  steps:
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - uses: nuget/setup-nuget@v2
      with:
        nuget-version: "6.x"
    - name: Generate Bindings
      shell: pwsh
      id: build_bindings
      run: |
        .\scripts\generate-bindings.ps1 -ImX ${{  inputs.ImX  }}
    - name: Generate NuGet packages
      shell: pwsh
      id: build_nugets
      run: |
        .\scripts\generate-nugets.ps1 -ImX ${{  inputs.ImX  }} -outputfolder ${{  inputs.NugetsPath  }}
    - name: Save nugets
      uses: actions/upload-artifact@v4
      with:
        name: ${{  inputs.ImX  }}-nugets
        path: ${{  inputs.NugetsPath  }}
        retention-days: 5
