name: CD Imgui
# This CD builds and publish what is currently on the repo.
# Addionally, periodically updates the submodules and try to publish a new nuget.
on:
  workflow_dispatch:
    inputs:
      publishEnabled:
        description: "Publish to Nuget.org"
        type: boolean
        required: false
        default: false
  schedule:
    - cron: "0 0 1 * *"

env:
  nugetsPath: "nupkgs"

jobs:
  build_publish_imgui_win:
    name: Generate Imgui nuget (windows only)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ./.github/actions/update-cimx
        if: ${{ github.event_name == 'schedule' }}
        with:
          Persists: False
      # TODO move build native steps to different jobs, commit, and then continue with Imgui on Windows
      - uses: ./.github/actions/build-native-win
        with:
          Target: Imgui
      - uses: ./.github/actions/generate-bindings-nugets
        id: nugets
        with:
          ImX: Imgui
          NugetsPath: ${{ env.nugetsPath }}
      - uses: ./.github/actions/publish-nugets
        if: ${{ success() && (github.event_name == 'schedule' || github.event.inputs.publishEnabled == 'true') }}
        with:
          NugetsPath: ${{ env.nugetsPath }}
          Token: ${{ secrets.EVERGINE_NUGETORG_TOKEN }}
      - name: Verify changes
        id: verify-changed-files
        shell: pwsh
        run: |
          .\scripts\verify-changes.ps1
      - name: Commit if appropiate
        if: ${{ success() && steps.verify-changed-files.outputs.files_changed == 'true' }} # don't commit if only dlls have been changed
        uses: EndBug/add-and-commit@v9
        with:
          message: Updating nugets
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
