name: CD

on:
  workflow_dispatch:
    inputs:
      publish-enabled:
        description: "Publish to Nuget.org"
        type: boolean
        required: false
        default: false

env:
  nugetsPath: "nupkgs"

jobs:
  # --- Build Native Libraries ---
  build-native-libs:
    uses: ./.github/workflows/build-native-libs.yml

  # --- Generate Bindings and NuGets ---
  generate-bindings:
    needs: build-native-libs
    runs-on: windows-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v5
      with:
        repository: ${{ github.repository }}
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.x

    - name: Download all artifacts
      uses: actions/download-artifact@v5
      with:
        path: artifacts

    - name: Copy artifacts to respective directories
      run: |
        Copy-Item -Recurse -Force -Path artifacts/cimgui-browser-wasm-artifacts/* -Destination Generator/Evergine.Bindings.Imgui/runtimes/
        Copy-Item -Recurse -Force -Path artifacts/cimgui-linux-arm64-artifacts/* -Destination Generator/Evergine.Bindings.Imgui/runtimes/
        Copy-Item -Recurse -Force -Path artifacts/cimgui-linux-x64-artifacts/* -Destination Generator/Evergine.Bindings.Imgui/runtimes/
        Copy-Item -Recurse -Force -Path artifacts/cimgui-osx-arm64-artifacts/* -Destination Generator/Evergine.Bindings.Imgui/runtimes/
        Copy-Item -Recurse -Force -Path artifacts/cimgui-osx-x64-artifacts/* -Destination Generator/Evergine.Bindings.Imgui/runtimes/
        Copy-Item -Recurse -Force -Path artifacts/cimgui-win-arm64-artifacts/* -Destination Generator/Evergine.Bindings.Imgui/runtimes/
        Copy-Item -Recurse -Force -Path artifacts/cimgui-win-x64-artifacts/* -Destination Generator/Evergine.Bindings.Imgui/runtimes/

    - name: Remove artifacts directory
      run: Remove-Item -Recurse -Force artifacts

    - name: Generate Bindings
      shell: pwsh
      run: ./build/scripts/Generate-All-Bindings.ps1

    - name: Commit changes (if any)
      uses: EvergineTeam/evergine-standards/.github/actions/commit-and-push-or-pr-update@main
      with:
        commit_message: "Updating runtimes"
        mode: auto
        labels: update

    - name: Generate NuGets
      uses: EvergineTeam/evergine-standards/.github/actions/binding-generate-nugets-dotnet@main
      with:
        script-path: './build/scripts/Generate-NuGets-DotNet.ps1'
        helpers-path: './build/scripts/Helpers.ps1'
        projects: './Generator/Evergine.Bindings.Imgui/Evergine.Bindings.Imgui.csproj'
        output-folder: ${{ env.nugetsPath }}
        revision: ${{ github.run_number }}

    - name: List generated NuGets
      run: |
        ls ${{ env.nugetsPath }}/*.nupkg

    - name: Upload Nuget Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nugets
        path: ${{ env.nugetsPath }}
        if-no-files-found: warn

    - name: Publish NuGet
      if: ${{ success() && inputs.publish-enabled == true }}
      env:
        token: ${{ secrets.EVERGINE_NUGETORG_TOKEN }}
      run: |
        cd ${{ env.nugetsPath }}
        ls *.nupkg
        dotnet nuget push "**/*.nupkg" --skip-duplicate --no-symbols -k "$env:token" -s https://api.nuget.org/v3/index.json
