name: CI Imgui
# This CI only builds what is currently on the repo
on:
  push:
    paths:
      - "Generator/ImguiGen/**"
      - "Generator/ImguizmoGen/**"
      - "Generator/ImnodesGen/**"
      - "Generator/ImplotGen/**"
      - "NativeLibraries/cimgui/**"
      - "NativeLibraries/extensions/**"
      - "scripts/deploy-win-native.ps1"
      - "scripts/generate-bindings.ps1"
      - "scripts/generate-nugets.ps1"

jobs:
  build_imgui_win:
    name: Build Imgui nuget (windows only)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions/build-native-win
        with:
          Target: Imgui
      - uses: ./.github/actions/build-native-win
        with:
          Target: Extensions
      - uses: ./.github/actions/generate-bindings-nugets
