name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v5
      with:
        repository: ${{ github.repository }}
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.x

    - name: Build
      run: dotnet build Generator/Generator.sln
