name: Generate and build bindings
on: push

jobs:
  build_cimgui_win:
    uses: ./.github/workflows/build-native-win.yml
    with:
      Target: Imgui

  build_extensions_win:
    uses: ./.github/workflows/build-native-win.yml
    with:
      Target: Extensions

  generate_imgui:
    needs: build_cimgui_win
    uses: ./.github/workflows/generate-bindings.yml
    with:
      ImX: Imgui

  generate_imguizmo:
    needs:
      - build_cimgui_win
      - build_extensions_win
    uses: ./.github/workflows/generate-bindings.yml
    with:
      ImX: Imguizmo

  generate_imnodes:
    needs:
      - build_cimgui_win
      - build_extensions_win
    uses: ./.github/workflows/generate-bindings.yml
    with:
      ImX: Imnodes

  generate_implot:
    needs:
      - build_cimgui_win
      - build_extensions_win
    uses: ./.github/workflows/generate-bindings.yml
    with:
      ImX: Implot
