name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v5
      with:
        repository: ${{ github.repository }}
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.x

    - name: Build
      run: |
        dotnet build Generator/ImguiGen/ImguiGen.csproj
        dotnet build Generator/ImguizmoGen/ImguizmoGen.csproj
        dotnet build Generator/ImnodesGen/ImnodesGen.csproj
        dotnet build Generator/ImplotGen/ImplotGen.csproj
        dotnet build Generator/Evergine.Bindings.Imgui/Evergine.Bindings.Imgui.csproj
