name: Generate and build bindings
on:
  workflow_call:
    inputs:
      ImX:
        description: "Values: 'Imgui', 'Imguizmo', 'Imnodes' or 'Implot'. Default 'Imgui'"
        type: string
        required: false
        default: Imgui

env:
  nugetOutputPath: ${{  'nupkgs'  }}

jobs:
  generate_and_build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            3.1.x
            5.x
            6.x
      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: "6.x"
      - name: Generate Bindings
        id: build_bindings
        run: |
          .\scripts\generate-bindings.ps1 -ImX ${{  inputs.ImX  }}
      - name: Generate NuGet packages
        id: build_nugets
        run: |
          .\scripts\generate-nugets.ps1 -ImX ${{  inputs.ImX  }} -outputfolder ${{  env.nugetOutputPath  }}
      # # - name: Commit if update
      # #   uses: EndBug/add-and-commit@v9
      # #   with:
      # #     message: Updating ${{  github.event.inputs.ImX  }} bindings
      - name: Upload nugets
        uses: actions/upload-artifact@v3
        with:
          name: ${{  github.event.inputs.ImX  }}-nugets
          path: ${{  env.nugetOutputPath  }}
