name: Update native sources
on:
  workflow_dispatch:

jobs:
  update_submodules:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ./.github/actions/update-cimx
        with:
          Persists: True
